### ISSUE TITLE
Synapse NOT WORKING?  (Password)

### ISSUE THREAD

**Issue by FilleDev** [PrismarineMC/MagmaBlock#2]
Hello! 

I cannot use Synapse. It says it's the wrong password but it's not! I'm going back to Nukkit if this issuse will not be fixed.

**Comment by Encritary** [comment]
@File14 I don't have that problem, check your file encoding. Use UTF-8 to solve this problem

**Comment by Encritary** [comment]
Or place here your exception's caught

**Comment by File14** [comment]
Worked now when I updated.
