### ISSUE TITLE
Add MrGegna

### ISSUE THREAD

**Issue by FilleDev** [PrismarineMC/MagmaBlock#3]
null

**Comment by daniktheboss** [comment]
Stop opening issues for small stuff

**Comment by File14** [comment]
"small stuff"? Do you call this small? This allows you to transfer player(s) to another server. How is that small? Also there's no chat or something like that so there's no other way to contact him.

**Comment by daniktheboss** [comment]
U just closed an issue about the same damn thing

**Comment by daniktheboss** [comment]
Open pr that's what's it for!

**Comment by File14** [comment]
"U just closed an issue about the same damn thing" May I have the link for the issuse that I just closed that was for the same thing?

**Comment by Encritary** [comment]
Added, but in other implementation. Look at the code
