### ISSUE TITLE
Synapse

### ISSUE THREAD

**Issue by ghost** [PrismarineMC/MagmaBlock#6]
Synapse not work. If i'm using ,she show : you uses 16 bit long key ,synapse not work. Why?

I'm using other password ,not default. @MrGenga

**Comment by FilleDev** [comment]
It works for me. Make sure your password is 16 letters long. If you are just using numbers as me you have to use "". So password: "1234567891011121"

**Comment by ghost** [comment]
Ok,thanks @File14

**Comment by FilleDev** [comment]
No problem! ^^

**Comment by ghost** [comment]
@File14  ,please you have one plugin for protection for nukkit?

**Comment by FilleDev** [comment]
What kind of protection plugin? What do you want?

**Comment by ghost** [comment]
For my skyblock server.

**Comment by FilleDev** [comment]
What kind of protection plugin?

**Comment by ghost** [comment]
One plugin of protection for protect spawn

**Comment by FilleDev** [comment]
Easy to code.

**Comment by ghost** [comment]
idk java.. i know php

**Comment by ghost** [comment]
you have one plugin for protection? e.g. regions ( but if i;m placed lava or water ,works )
