### ISSUE TITLE
synapse

### ISSUE THREAD

**Issue by ghost** [PrismarineMC/MagmaBlock#8]
#### Issue description

Synapse not work
#### Steps to reproduce the issue

start server with synapse
#### OS and versions

- Prismarine: https://github.com/PrismarineMC/MagmaBlock/commit/c105eb7c47b7eaa1c3e6e0ced0e3eb3e40623353
- PHP: java 8
- Server OS: ubuntu 16.04.1 LTS 64bit
- Game version: 0.15.6 alpha
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ghost** [comment]
16:31:46 [ALERT] java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
        at org.itxtech.synapseapi.SynapseAPI.<init>(SynapseAPI.java:74)
        at cn.nukkit.Server.<init>(Server.java:484)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

16:31:46 [INFO] Stopping other threads
16:31:46 [EMERGENCY] RakNet crashed!

**Comment by ghost** [comment]
Wtf

**Comment by Encritary** [comment]
It is your fail @NycuRO -_-
REVERT IT, I SAID!
